# MCMC simulation settings
file_base: "data/Q0020"
snapnum: 0
output_base: "output/Q20/HIGHZ_NGC_Q20_500"

# Model parameters
v_th: 467.4
delta_v: 89.4
ns_type: 0

n_mc: 500
kmax: 0.4

step_covariance:
  - [125.82, 268.14]
  - [268.14, 576.97]
